---

logging:
  level:
    org.springframework: INFO

server:
  port: 9125

application:
  jwt:
    jwtSecret: NyashMyashSecretKeyNyashMyashSecretKeyNyashMyashSecretKeyNyashMyashSecretKeyNyashMyashSecretKey
    jwtExpirationMs: 3600000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/travellizer_mono_db
    username: postgres
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update




#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 458290253646-9kc4geblrg0vn1tomu77ii8vt28fm151.apps.googleusercontent.com
#            client-secret: j5pOCJ_cWYzztWQHZqSOl249
#            access-token: https://www.googleapis.com/oauth2/v4/token
#            user-authorisation-uri: https://accounts.google.com/o/oauth2/v2/auth
#            client-authentication-scheme: form
#            scope:
#              - openid
#              - email
#              - profile



